baseurl = "localhost"
title = "/home/techyporcupine"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "techyporcupine"
  info = "A highschooler who has too much time and not enough projects"
  description = "Caleb's personal website"
  keywords = "blog,developer,personal,networking"
  avatarurl = "images/pfp.png"

  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[params.meta]
  favicon = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/techyporcupine/"

# Menu links
[[menu.main]]
  name = "~/equipment"
  weight = 1
  url  = "equipment/"
[[menu.main]]
  name = "~/projects"
  weight = 2
  url = "projects/"
[[menu.main]]
  name = "~/about"
  weight = 3
  url = "about/"